version: '1.2'
name: 'docker-web-dev-environment'

volumes:
  volume_data:
    name: <your-volume-name>
    driver: local
    driver_opts:
      type: none
      device: <path-to-your-source>
      o: bind
#  smtp4dev-data:

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - volume_data:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: './docker/php-fpm'
    volumes:
      - ./docker/php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - volume_data:/var/www/html
# If you need a smtp server next to your dev environment.
# https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
#  smtp4dev:
#    image: rnwood/smtp4dev:v3
#    ports:
#      - '5000:80'
#      - '25:25'
#      - '143:143'
#    volumes:
#      - smtp4dev-data:/smtp4dev
#    environment:
#      - ServerOptions__Urls=http://*:80
#      - ServerOptions__HostName=smtp4dev