version: '1.1'
name: 'docker-web-dev-environment'

volumes:
  volume_data:
    name: <your-volume-name>
    driver: local
    driver_opts:
      type: none
      device: <path-to-your-source>
      o: bind

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - volume_data:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: './docker/php-fpm'
    volumes:
      - ./docker/php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - volume_data:/var/www/html
